name: Deploy MkDocs Site to Netlify

on:
  push:
    branches:
      - rockydocs2-netlify

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout content repo (rockydocs2)
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Checkout MkDocs app repo (wsoyinka/docs.rockylinux.org)
      uses: actions/checkout@v4
      with:
        repository: wsoyinka/docs.rockylinux.org
        path: mkdocs-app
        ref: netlify
        fetch-depth: 1

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install MkDocs dependencies
      run: |
        pip install -r mkdocs-app/requirements.txt

    - name: Copy content into mkdocs-app/content
      run: |
        pwd
        mkdir -p mkdocs-app/docs/content
        cp -r docs mkdocs-app/docs/content/
        echo "Running ls -l ."
        ls -l .
        echo "Now Running ls -l mkdocs-app/"
        ls -l mkdocs-app/
        echo "Now Running ls -l mkdocs-app/docs/"
        ls -l mkdocs-app/docs/
        echo "Now Running ls -l mkdocs-app/docs/content/"
        ls -l mkdocs-app/docs/content/

    - name: Build + deploy versions with mike
      run: |
        cd mkdocs-app
        git config --global user.name "wsoyinka"
        git config --global user.email "webmaster@rockylinux.org"
        git fetch origin
        if git ls-remote --exit-code --heads origin gh-pages; then
          echo "gh-pages exists. Checking it out."
          git checkout gh-pages
          git pull origin gh-pages
        else
          echo "gh-pages does not exist. Creating orphan branch."
          git checkout --orphan gh-pages
          git reset --hard
          git commit --allow-empty -m "Initial gh-pages commit"
          git push origin gh-pages
        fi

        # Now safe to deploy versions
        mike deploy 8
        mike deploy 9
        mike deploy 10 latest
        mike set-default latest
        git push origin gh-pages
